2012/03/09 22:13:33 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`museu2`.`Object_Work_Records`, CONSTRAINT `FKObject_Wor394619` FOREIGN KEY (`RecordType`) REFERENCES `RecordTypes` (`id_recordTypes`)). The SQL statement executed was: INSERT INTO `Object_Work_Records` (`displayCreator`, `displayMeasurements`, `displayMaterialsTech`, `displayCreationDate`, `RecordType`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4).
in /opt/lampp/htdocs/yii/testdrive/protected/controllers/Object_Work_RecordsController.php (76)
in /opt/lampp/htdocs/yii/testdrive/index.php (13)
2012/03/09 22:13:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`museu2`.`Object_Work_Records`, CONSTRAINT `FKObject_Wor394619` FOREIGN KEY (`RecordType`) REFERENCES `RecordTypes` (`id_recordTypes`)). The SQL statement executed was: INSERT INTO `Object_Work_Records` (`displayCreator`, `displayMeasurements`, `displayMaterialsTech`, `displayCreationDate`, `RecordType`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4)' in /opt/lampp/htdocs/yii/framework/db/CDbCommand.php:354
Stack trace:
#0 /opt/lampp/htdocs/yii/framework/db/ar/CActiveRecord.php(1014): CDbCommand->execute()
#1 /opt/lampp/htdocs/yii/framework/db/ar/CActiveRecord.php(787): CActiveRecord->insert(NULL)
#2 /opt/lampp/htdocs/yii/testdrive/protected/controllers/Object_Work_RecordsController.php(76): CActiveRecord->save()
#3 /opt/lampp/htdocs/yii/framework/web/actions/CInlineAction.php(50): Object_Work_RecordsController->actionCreate()
#4 /opt/lampp/htdocs/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#5 /opt/lampp/htdocs/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 /opt/lampp/htdocs/yii/framework/web/filters/CFilter.php(41): CFilterChain->run()
#7 /opt/lampp/htdocs/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#8 /opt/lampp/htdocs/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#9 /opt/lampp/htdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 /opt/lampp/htdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#11 /opt/lampp/htdocs/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /opt/lampp/htdocs/yii/framework/web/CWebApplication.php(276): CController->run('create')
#13 /opt/lampp/htdocs/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('object_Work_Rec...')
#14 /opt/lampp/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /opt/lampp/htdocs/yii/testdrive/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdrive/index.php?r=object_Work_Records/create
HTTP_REFERER=http://localhost/yii/testdrive/index.php?r=object_Work_Records/create
---
2012/04/30 10:45:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /opt/lampp/htdocs/yii/framework/web/CWebApplication.php:280
Stack trace:
#0 /opt/lampp/htdocs/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('gii')
#1 /opt/lampp/htdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /opt/lampp/htdocs/yii/testdrive/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/testdrive/index.php?r=gii
---
